### ISSUE TITLE
Command event not firing

### ISSUE THREAD

**Issue by sigmasoldi3r** [garrettjoecox/scriptserver-command#3] opened 2018-10-02 09:01 UTC
Tested script:

```js
const config = require('./server.config');
const Server = require('scriptserver');

const app = new Server({
  core: {
    jar: config.jar,
    args: [
      ...config.args
    ]
  },
  command: { // With and without this option yields the same result
    prefix: '!'
  }
});

app.use(require('scriptserver-command'));

app.command('test', evt => {
  console.log(evt.timestamp, ' >> Test command!');
  app.send(`kill ${evt.player}`);
});

app.start();
```

Also tried without specifying the `command: {prefix: ... }` option, and following chat messages does not produce any output in the console, aside from the server output:

+ `!test`
+ `~test`
+ `test`
+ `\test`

```
[10:47:45] [Server thread/INFO] [minecraft/DedicatedServer]: <player> !test
[10:47:48] [Server thread/INFO] [minecraft/DedicatedServer]: <player> test
[10:47:50] [Server thread/INFO] [minecraft/DedicatedServer]: <player> ~test
[10:47:52] [Server thread/INFO] [minecraft/DedicatedServer]: <player> \test
```

**Versions:**

Node `v10.7.0`
NPM `6.4.1`
scriptserver `latest`
scriptserver-command `latest`

**Comment by garrettjoecox** [comment] 2020-05-01 02:30
Unable to reproduce, also really old ticket so closing for now. Submit another if you experience this in the newest version

**Closed as completed by garrettjoecox** 2020-05-01 02:30 UTC
